#!/bin/sh


while :
do
	START=$(date +%s)
	perl ./backend_devices.pl
	perl ./backend_servers.pl
	END=$(date +%s)

	script_time=$(($END-$START))
	sleep_by=$((60 - $script_time))
	echo "ANM2"
	echo "Script Run time: $script_time"
	echo "ANM2"
	
	sleep $sleep_by
done
